# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2666e04fdaaba5eeedc2361df6569196ef7212d920cb08d1611a1c92cefaa0869eaeb9b06f66fb349142cab6e80b9769f3252e6c4bf64ebeef95baf6d04b6f01

test:
  secret_key_base: 4b61b49595e849205e9d14738527be2fe19c6ecb442506094e59411c698e007edaa695f717cfb8fd0eb88e2ef28cb14dd65848ac42cfb00ec88b6bebf3c0afdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
